--------------------------------------------------------------------------------
-- king_wen_shotgun_pkg.vhd
-- Auto-generated from Sovereign ICT v2.0 dashboard data + OEIS A000000
-- 64 Hexagrams × 26 fields, deterministic, no pseudo-RNG
-- Target: Xilinx Zynq UltraScale+ ZU7EV
--------------------------------------------------------------------------------

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

package king_wen_shotgun_pkg is

    ---------------------------------------------------------------------------
    -- Fixed-point types
    ---------------------------------------------------------------------------
    subtype t_q88 is signed(15 downto 0);     -- Q8.8 signed
    subtype t_uq88 is unsigned(15 downto 0);  -- Q8.8 unsigned
    subtype t_uq016 is unsigned(15 downto 0); -- Q0.16 unsigned

    ---------------------------------------------------------------------------
    -- Hexagram record: all 26 fields packed
    ---------------------------------------------------------------------------
    type t_hexagram is record
        id              : unsigned(6 downto 0);   -- 1..64
        yao             : unsigned(5 downto 0);   -- binary pattern
        upper_trigram   : unsigned(2 downto 0);   -- Qian=0..Li=7
        lower_trigram   : unsigned(2 downto 0);
        category        : unsigned(1 downto 0);   -- sovereign=0..boundary=3
        action          : unsigned(1 downto 0);   -- ASSERT=0..WAIT=3
        agent           : unsigned(1 downto 0);   -- architect=0..guardian=3
        domain          : unsigned(1 downto 0);   -- assertion=0..patience=3
        element         : unsigned(2 downto 0);   -- heaven=0..fire=7
        coder           : unsigned(3 downto 0);   -- 12 specialties
        rs3             : unsigned(3 downto 0);   -- 10 RS3 actionables
        motion          : std_logic;              -- 0=centripetal, 1=centrifugal
        voice           : unsigned(3 downto 0);   -- 9 voice modes
        intent          : unsigned(3 downto 0);   -- understand=0
        density         : unsigned(1 downto 0);   -- OEIS A000000: 0=valley,1=terrace,2=peak
        vortex_tension  : t_q88;                  -- Schauberger physics
        suction         : t_uq88;
        chaos           : t_uq016;                -- Emotional vector (5D)
        whimsy          : t_uq016;
        dark            : t_uq016;
        coherence       : t_uq016;
        voice_weight    : t_uq016;
        intensity       : t_uq016;
        tx              : t_q88;                  -- Terrain coordinates
        ty              : t_q88;
    end record;

    ---------------------------------------------------------------------------
    -- Array types for shotgun output
    ---------------------------------------------------------------------------
    type t_hexagram_array is array (0 to 63) of t_hexagram;
    type t_density_array is array (0 to 63) of unsigned(1 downto 0);
    type t_coupling_matrix is array (0 to 3, 0 to 3) of unsigned(7 downto 0); -- Q0.8

    ---------------------------------------------------------------------------
    -- Category coupling strengths (from dashboard: SOV↔DISS=0.90, etc.)
    -- Stored as Q0.8: 0.90 = 230, 0.50 = 128, 0.10 = 26, etc.
    ---------------------------------------------------------------------------
    constant C_COUPLING : t_coupling_matrix := (
        --              SOV    DISS   TRANS  BOUND
        /* SOV   */  (x"00", x"E6", x"80", x"1A"),
        /* DISS  */  (x"E6", x"00", x"B3", x"99"),
        /* TRANS */  (x"80", x"B3", x"00", x"66"),
        /* BOUND */  (x"1A", x"99", x"66", x"00")
    );

    ---------------------------------------------------------------------------
    -- Helper: build hexagram from encoded fields
    ---------------------------------------------------------------------------
    function make_hexagram(
        id_val   : integer;
        yao_val  : integer;
        up_tri   : integer;
        lo_tri   : integer;
        cat_val  : integer;
        act_val  : integer;
        agt_val  : integer;
        dom_val  : integer;
        elem_val : integer;
        coder_val: integer;
        rs3_val  : integer;
        mot_val  : integer;
        voice_val: integer;
        intent_val: integer;
        dens_val : integer;
        vtx_val  : integer;
        suc_val  : integer;
        chaos_val: integer;
        whims_val: integer;
        dark_val : integer;
        coh_val  : integer;
        vw_val   : integer;
        intens_val: integer;
        tx_val   : integer;
        ty_val   : integer
    ) return t_hexagram;

    ---------------------------------------------------------------------------
    -- The 64 King Wen hexagrams (canonical order)
    -- Generated from deterministic placement on 8x8 sovereign world grid
    ---------------------------------------------------------------------------
    constant C_ALL_HEXAGRAMS : t_hexagram_array := (
        -- Hexagram  1: The Creative
        0 => make_hexagram(
            id_val    => 1,
            yao_val   => 63,
            up_tri    => 0,
            lo_tri    => 0,
            cat_val   => 0,
            act_val   => 0,
            agt_val   => 0,
            dom_val   => 0,
            elem_val  => 0,
            coder_val => 0,
            rs3_val   => 0,
            mot_val   => 0,
            voice_val => 0,
            intent_val=> 0,
            dens_val  => 0,
            vtx_val   => 16#0000,
            suc_val   => 16#0002,
            chaos_val => 16#2FF3,
            whims_val => 16#1198,
            dark_val  => 16#2AE5,
            coh_val   => 16#8759,
            vw_val    => 16#A0DE,
            intens_val=> 16#0A3D,
            tx_val    => 16#E5C0,
            ty_val    => 16#1A40
        ),
        -- Hexagram  2: The Receptive
        1 => make_hexagram(
            id_val    => 2,
            yao_val   => 0,
            up_tri    => 1,
            lo_tri    => 1,
            cat_val   => 2,
            act_val   => 1,
            agt_val   => 1,
            dom_val   => 1,
            elem_val  => 1,
            coder_val => 1,
            rs3_val   => 1,
            mot_val   => 0,
            voice_val => 1,
            intent_val=> 0,
            dens_val  => 1,
            vtx_val   => 16#0000,
            suc_val   => 16#0001,
            chaos_val => 16#0A7E,
            whims_val => 16#2062,
            dark_val  => 16#0865,
            coh_val   => 16#60E7,
            vw_val    => 16#63C0,
            intens_val=> 16#0A3D,
            tx_val    => 16#ED40,
            ty_val    => 16#1A40
        ),
        -- Hexagram  3: Difficulty at the Be
        2 => make_hexagram(
            id_val    => 3,
            yao_val   => 17,
            up_tri    => 2,
            lo_tri    => 3,
            cat_val   => 1,
            act_val   => 2,
            agt_val   => 2,
            dom_val   => 2,
            elem_val  => 2,
            coder_val => 2,
            rs3_val   => 2,
            mot_val   => 0,
            voice_val => 2,
            intent_val=> 0,
            dens_val  => 2,
            vtx_val   => 16#0000,
            suc_val   => 16#0003,
            chaos_val => 16#218F,
            whims_val => 16#213D,
            dark_val  => 16#184C,
            coh_val   => 16#6629,
            vw_val    => 16#729A,
            intens_val=> 16#0A3D,
            tx_val    => 16#F4C0,
            ty_val    => 16#1A40
        ),
        -- Hexagram  4: Youthful Folly
        3 => make_hexagram(
            id_val    => 4,
            yao_val   => 34,
            up_tri    => 3,
            lo_tri    => 4,
            cat_val   => 2,
            act_val   => 3,
            agt_val   => 1,
            dom_val   => 3,
            elem_val  => 3,
            coder_val => 3,
            rs3_val   => 3,
            mot_val   => 0,
            voice_val => 2,
            intent_val=> 0,
            dens_val  => 1,
            vtx_val   => 16#0000,
            suc_val   => 16#0002,
            chaos_val => 16#1BA5,
            whims_val => 16#18F5,
            dark_val  => 16#1FFC,
            coh_val   => 16#673A,
            vw_val    => 16#70D4,
            intens_val=> 16#0A3D,
            tx_val    => 16#FC40,
            ty_val    => 16#1A40
        ),
        -- Hexagram  5: Waiting
        4 => make_hexagram(
            id_val    => 5,
            yao_val   => 23,
            up_tri    => 0,
            lo_tri    => 3,
            cat_val   => 1,
            act_val   => 3,
            agt_val   => 2,
            dom_val   => 3,
            elem_val  => 0,
            coder_val => 4,
            rs3_val   => 4,
            mot_val   => 0,
            voice_val => 2,
            intent_val=> 0,
            dens_val  => 0,
            vtx_val   => 16#0000,
            suc_val   => 16#0001,
            chaos_val => 16#16E9,
            whims_val => 16#12B6,
            dark_val  => 16#26A0,
            coh_val   => 16#7949,
            vw_val    => 16#888D,
            intens_val=> 16#0A3D,
            tx_val    => 16#03C0,
            ty_val    => 16#1A40
        ),
        -- Hexagram  6: Conflict
        5 => make_hexagram(
            id_val    => 6,
            yao_val   => 58,
            up_tri    => 3,
            lo_tri    => 0,
            cat_val   => 2,
            act_val   => 0,
            agt_val   => 1,
            dom_val   => 0,
            elem_val  => 3,
            coder_val => 5,
            rs3_val   => 5,
            mot_val   => 0,
            voice_val => 2,
            intent_val=> 0,
            dens_val  => 1,
            vtx_val   => 16#0000,
            suc_val   => 16#0001,
            chaos_val => 16#1BA5,
            whims_val => 16#121F,
            dark_val  => 16#2C8A,
            coh_val   => 16#748D,
            vw_val    => 16#8598,
            intens_val=> 16#0A3D,
            tx_val    => 16#0B40,
            ty_val    => 16#1A40
        ),
        -- Hexagram  7: The Army
        6 => make_hexagram(
            id_val    => 7,
            yao_val   => 2,
            up_tri    => 3,
            lo_tri    => 1,
            cat_val   => 0,
            act_val   => 0,
            agt_val   => 0,
            dom_val   => 0,
            elem_val  => 3,
            coder_val => 6,
            rs3_val   => 6,
            mot_val   => 0,
            voice_val => 2,
            intent_val=> 0,
            dens_val  => 2,
            vtx_val   => 16#0000,
            suc_val   => 16#0002,
            chaos_val => 16#1A76,
            whims_val => 16#1D8E,
            dark_val  => 16#1A23,
            coh_val   => 16#5C6F,
            vw_val    => 16#67A0,
            intens_val=> 16#0A3D,
            tx_val    => 16#12C0,
            ty_val    => 16#1A40
        ),
        -- Hexagram  8: Holding Together
        7 => make_hexagram(
            id_val    => 8,
            yao_val   => 16,
            up_tri    => 1,
            lo_tri    => 3,
            cat_val   => 2,
            act_val   => 1,
            agt_val   => 1,
            dom_val   => 1,
            elem_val  => 1,
            coder_val => 7,
            rs3_val   => 7,
            mot_val   => 0,
            voice_val => 3,
            intent_val=> 0,
            dens_val  => 1,
            vtx_val   => 16#0000,
            suc_val   => 16#0001,
            chaos_val => 16#1523,
            whims_val => 16#1CF7,
            dark_val  => 16#1439,
            coh_val   => 16#61C2,
            vw_val    => 16#6967,
            intens_val=> 16#0A3D,
            tx_val    => 16#1A40,
            ty_val    => 16#1A40
        ),
        -- Hexagram  9: Taming Power of the 
        8 => make_hexagram(
            id_val    => 9,
            yao_val   => 55,
            up_tri    => 0,
            lo_tri    => 5,
            cat_val   => 1,
            act_val   => 2,
            agt_val   => 2,
            dom_val   => 2,
            elem_val  => 0,
            coder_val => 8,
            rs3_val   => 8,
            mot_val   => 0,
            voice_val => 2,
            intent_val=> 0,
            dens_val  => 1,
            vtx_val   => 16#0005,
            suc_val   => 16#0001,
            chaos_val => 16#1B50,
            whims_val => 16#18B1,
            dark_val  => 16#2407,
            coh_val   => 16#8180,
            vw_val    => 16#93A5,
            intens_val=> 16#0A3D,
            tx_val    => 16#E5C0,
            ty_val    => 16#12C0
        ),
        -- Hexagram 10: Treading
        9 => make_hexagram(
            id_val    => 10,
            yao_val   => 59,
            up_tri    => 6,
            lo_tri    => 0,
            cat_val   => 0,
            act_val   => 2,
            agt_val   => 0,
            dom_val   => 2,
            elem_val  => 6,
            coder_val => 9,
            rs3_val   => 9,
            mot_val   => 0,
            voice_val => 2,
            intent_val=> 0,
            dens_val  => 1,
            vtx_val   => 16#000A,
            suc_val   => 16#0002,
            chaos_val => 16#1E46,
            whims_val => 16#1FCA,
            dark_val  => 16#22D8,
            coh_val   => 16#8180,
            vw_val    => 16#930E,
            intens_val=> 16#0A3D,
            tx_val    => 16#ED40,
            ty_val    => 16#12C0
        ),
        -- Hexagram 11: Peace
        10 => make_hexagram(
            id_val    => 11,
            yao_val   => 7,
            up_tri    => 0,
            lo_tri    => 1,
            cat_val   => 2,
            act_val   => 1,
            agt_val   => 1,
            dom_val   => 1,
            elem_val  => 0,
            coder_val => 10,
            rs3_val   => 0,
            mot_val   => 0,
            voice_val => 4,
            intent_val=> 0,
            dens_val  => 1,
            vtx_val   => 16#0010,
            suc_val   => 16#0001,
            chaos_val => 16#0C44,
            whims_val => 16#1621,
            dark_val  => 16#12BE,
            coh_val   => 16#81A1,
            vw_val    => 16#82E6,
            intens_val=> 16#0A3D,
            tx_val    => 16#F4C0,
            ty_val    => 16#12C0
        ),
        -- Hexagram 12: Standstill
        11 => make_hexagram(
            id_val    => 12,
            yao_val   => 56,
            up_tri    => 1,
            lo_tri    => 0,
            cat_val   => 3,
            act_val   => 3,
            agt_val   => 3,
            dom_val   => 3,
            elem_val  => 1,
            coder_val => 11,
            rs3_val   => 1,
            mot_val   => 0,
            voice_val => 5,
            intent_val=> 0,
            dens_val  => 1,
            vtx_val   => 16#0015,
            suc_val   => 16#0000,
            chaos_val => 16#0BAC,
            whims_val => 16#14F2,
            dark_val  => 16#12BE,
            coh_val   => 16#8239,
            vw_val    => 16#81B7,
            intens_val=> 16#0A3D,
            tx_val    => 16#FC40,
            ty_val    => 16#12C0
        ),
        -- Hexagram 13: Fellowship with Men
        12 => make_hexagram(
            id_val    => 13,
            yao_val   => 47,
            up_tri    => 0,
            lo_tri    => 7,
            cat_val   => 2,
            act_val   => 0,
            agt_val   => 1,
            dom_val   => 0,
            elem_val  => 0,
            coder_val => 0,
            rs3_val   => 2,
            mot_val   => 0,
            voice_val => 2,
            intent_val=> 0,
            dens_val  => 1,
            vtx_val   => 16#001A,
            suc_val   => 16#0001,
            chaos_val => 16#1B50,
            whims_val => 16#13F6,
            dark_val  => 16#2407,
            coh_val   => 16#83DD,
            vw_val    => 16#9603,
            intens_val=> 16#0A3D,
            tx_val    => 16#03C0,
            ty_val    => 16#12C0
        ),
        -- Hexagram 14: Possession in Great 
        13 => make_hexagram(
            id_val    => 14,
            yao_val   => 61,
            up_tri    => 7,
            lo_tri    => 0,
            cat_val   => 0,
            act_val   => 0,
            agt_val   => 0,
            dom_val   => 0,
            elem_val  => 7,
            coder_val => 1,
            rs3_val   => 3,
            mot_val   => 0,
            voice_val => 2,
            intent_val=> 0,
            dens_val  => 1,
            vtx_val   => 16#001F,
            suc_val   => 16#0001,
            chaos_val => 16#1C7F,
            whims_val => 16#1525,
            dark_val  => 16#249F,
            coh_val   => 16#8346,
            vw_val    => 16#952F,
            intens_val=> 16#0A3D,
            tx_val    => 16#0B40,
            ty_val    => 16#12C0
        ),
        -- Hexagram 15: Modesty
        14 => make_hexagram(
            id_val    => 15,
            yao_val   => 8,
            up_tri    => 1,
            lo_tri    => 4,
            cat_val   => 2,
            act_val   => 1,
            agt_val   => 1,
            dom_val   => 1,
            elem_val  => 1,
            coder_val => 2,
            rs3_val   => 4,
            mot_val   => 0,
            voice_val => 2,
            intent_val=> 0,
            dens_val  => 1,
            vtx_val   => 16#0025,
            suc_val   => 16#0001,
            chaos_val => 16#0BAC,
            whims_val => 16#1BC8,
            dark_val  => 16#0BF1,
            coh_val   => 16#6BB2,
            vw_val    => 16#6CF3,
            intens_val=> 16#0A3D,
            tx_val    => 16#12C0,
            ty_val    => 16#12C0
        ),
        -- Hexagram 16: Enthusiasm
        15 => make_hexagram(
            id_val    => 16,
            yao_val   => 4,
            up_tri    => 2,
            lo_tri    => 1,
            cat_val   => 1,
            act_val   => 2,
            agt_val   => 2,
            dom_val   => 2,
            elem_val  => 2,
            coder_val => 3,
            rs3_val   => 5,
            mot_val   => 0,
            voice_val => 2,
            intent_val=> 0,
            dens_val  => 1,
            vtx_val   => 16#0000,
            suc_val   => 16#0002,
            chaos_val => 16#16E9,
            whims_val => 16#24A7,
            dark_val  => 16#0A2B,
            coh_val   => 16#654E,
            vw_val    => 16#6CF3,
            intens_val=> 16#0A3D,
            tx_val    => 16#1A40,
            ty_val    => 16#12C0
        ),
        -- Hexagram 17: Following
        16 => make_hexagram(
            id_val    => 17,
            yao_val   => 38,
            up_tri    => 2,
            lo_tri    => 6,
            cat_val   => 2,
            act_val   => 1,
            agt_val   => 1,
            dom_val   => 1,
            elem_val  => 2,
            coder_val => 4,
            rs3_val   => 6,
            mot_val   => 0,
            voice_val => 2,
            intent_val=> 0,
            dens_val  => 2,
            vtx_val   => 16#000A,
            suc_val   => 16#0002,
            chaos_val => 16#1BA5,
            whims_val => 16#2748,
            dark_val  => 16#1485,
            coh_val   => 16#78C2,
            vw_val    => 16#7EA4,
            intens_val=> 16#0A3D,
            tx_val    => 16#E5C0,
            ty_val    => 16#0B40
        ),
        -- Hexagram 18: Work on Decayed
        17 => make_hexagram(
            id_val    => 18,
            yao_val   => 25,
            up_tri    => 5,
            lo_tri    => 4,
            cat_val   => 1,
            act_val   => 2,
            agt_val   => 2,
            dom_val   => 2,
            elem_val  => 5,
            coder_val => 5,
            rs3_val   => 7,
            mot_val   => 0,
            voice_val => 2,
            intent_val=> 0,
            dens_val  => 1,
            vtx_val   => 16#0015,
            suc_val   => 16#0001,
            chaos_val => 16#10FF,
            whims_val => 16#20C7,
            dark_val  => 16#1811,
            coh_val   => 16#7B99,
            vw_val    => 16#7CDE,
            intens_val=> 16#0A3D,
            tx_val    => 16#ED40,
            ty_val    => 16#0B40
        ),
        -- Hexagram 19: Approach
        18 => make_hexagram(
            id_val    => 19,
            yao_val   => 48,
            up_tri    => 1,
            lo_tri    => 6,
            cat_val   => 2,
            act_val   => 1,
            agt_val   => 1,
            dom_val   => 1,
            elem_val  => 1,
            coder_val => 6,
            rs3_val   => 8,
            mot_val   => 0,
            voice_val => 2,
            intent_val=> 0,
            dens_val  => 0,
            vtx_val   => 16#001F,
            suc_val   => 16#0001,
            chaos_val => 16#0F39,
            whims_val => 16#2303,
            dark_val  => 16#0AB1,
            coh_val   => 16#745B,
            vw_val    => 16#7571,
            intens_val=> 16#0A3D,
            tx_val    => 16#F4C0,
            ty_val    => 16#0B40
        ),
        -- Hexagram 20: Contemplation
        19 => make_hexagram(
            id_val    => 20,
            yao_val   => 3,
            up_tri    => 5,
            lo_tri    => 1,
            cat_val   => 3,
            act_val   => 3,
            agt_val   => 3,
            dom_val   => 3,
            elem_val  => 5,
            coder_val => 7,
            rs3_val   => 9,
            mot_val   => 0,
            voice_val => 2,
            intent_val=> 0,
            dens_val  => 1,
            vtx_val   => 16#002A,
            suc_val   => 16#0001,
            chaos_val => 16#0FD0,
            whims_val => 16#2560,
            dark_val  => 16#0C78,
            coh_val   => 16#70CE,
            vw_val    => 16#73AA,
            intens_val=> 16#0A3D,
            tx_val    => 16#FC40,
            ty_val    => 16#0B40
        ),
        -- Hexagram 21: Biting Through
        20 => make_hexagram(
            id_val    => 21,
            yao_val   => 37,
            up_tri    => 2,
            lo_tri    => 7,
            cat_val   => 2,
            act_val   => 0,
            agt_val   => 1,
            dom_val   => 0,
            elem_val  => 2,
            coder_val => 8,
            rs3_val   => 0,
            mot_val   => 0,
            voice_val => 2,
            intent_val=> 0,
            dens_val  => 2,
            vtx_val   => 16#0034,
            suc_val   => 16#0002,
            chaos_val => 16#1A76,
            whims_val => 16#202F,
            dark_val  => 16#15B3,
            coh_val   => 16#79F1,
            vw_val    => 16#800F,
            intens_val=> 16#0A3D,
            tx_val    => 16#03C0,
            ty_val    => 16#0B40
        ),
        -- Hexagram 22: Grace
        21 => make_hexagram(
            id_val    => 22,
            yao_val   => 41,
            up_tri    => 7,
            lo_tri    => 4,
            cat_val   => 3,
            act_val   => 3,
            agt_val   => 3,
            dom_val   => 3,
            elem_val  => 7,
            coder_val => 9,
            rs3_val   => 1,
            mot_val   => 0,
            voice_val => 2,
            intent_val=> 0,
            dens_val  => 1,
            vtx_val   => 16#003F,
            suc_val   => 16#0001,
            chaos_val => 16#10FF,
            whims_val => 16#19AE,
            dark_val  => 16#1811,
            coh_val   => 16#7F25,
            vw_val    => 16#806A,
            intens_val=> 16#0A3D,
            tx_val    => 16#0B40,
            ty_val    => 16#0B40
        ),
        -- Hexagram 23: Splitting Apart
        22 => make_hexagram(
            id_val    => 23,
            yao_val   => 1,
            up_tri    => 1,
            lo_tri    => 4,
            cat_val   => 1,
            act_val   => 3,
            agt_val   => 2,
            dom_val   => 3,
            elem_val  => 1,
            coder_val => 10,
            rs3_val   => 2,
            mot_val   => 0,
            voice_val => 2,
            intent_val=> 0,
            dens_val  => 0,
            vtx_val   => 16#0049,
            suc_val   => 16#0001,
            chaos_val => 16#0BAC,
            whims_val => 16#1BC8,
            dark_val  => 16#0BF1,
            coh_val   => 16#6BB2,
            vw_val    => 16#6CF3,
            intens_val=> 16#0A3D,
            tx_val    => 16#12C0,
            ty_val    => 16#0B40
        ),
        -- Hexagram 24: Return
        23 => make_hexagram(
            id_val    => 24,
            yao_val   => 32,
            up_tri    => 2,
            lo_tri    => 1,
            cat_val   => 2,
            act_val   => 1,
            agt_val   => 1,
            dom_val   => 1,
            elem_val  => 2,
            coder_val => 11,
            rs3_val   => 3,
            mot_val   => 0,
            voice_val => 2,
            intent_val=> 0,
            dens_val  => 1,
            vtx_val   => 16#0000,
            suc_val   => 16#0002,
            chaos_val => 16#16E9,
            whims_val => 16#24A7,
            dark_val  => 16#0A2B,
            coh_val   => 16#654E,
            vw_val    => 16#6CF3,
            intens_val=> 16#0A3D,
            tx_val    => 16#1A40,
            ty_val    => 16#0B40
        ),
        -- Hexagram 25: Innocence
        24 => make_hexagram(
            id_val    => 25,
            yao_val   => 39,
            up_tri    => 2,
            lo_tri    => 0,
            cat_val   => 0,
            act_val   => 0,
            agt_val   => 0,
            dom_val   => 0,
            elem_val  => 2,
            coder_val => 0,
            rs3_val   => 4,
            mot_val   => 0,
            voice_val => 2,
            intent_val=> 0,
            dens_val  => 1,
            vtx_val   => 16#0010,
            suc_val   => 16#0001,
            chaos_val => 16#1818,
            whims_val => 16#1938,
            dark_val  => 16#1C92,
            coh_val   => 16#7D6D,
            vw_val    => 16#8AEB,
            intens_val=> 16#0A3D,
            tx_val    => 16#E5C0,
            ty_val    => 16#03C0
        ),
        -- Hexagram 26: Taming Power of the 
        25 => make_hexagram(
            id_val    => 26,
            yao_val   => 57,
            up_tri    => 0,
            lo_tri    => 4,
            cat_val   => 3,
            act_val   => 2,
            agt_val   => 3,
            dom_val   => 2,
            elem_val  => 0,
            coder_val => 1,
            rs3_val   => 5,
            mot_val   => 0,
            voice_val => 2,
            intent_val=> 0,
            dens_val  => 1,
            vtx_val   => 16#001F,
            suc_val   => 16#0000,
            chaos_val => 16#0D73,
            whims_val => 16#1188,
            dark_val  => 16#1E58,
            coh_val   => 16#8339,
            vw_val    => 16#8C1A,
            intens_val=> 16#0A3D,
            tx_val    => 16#ED40,
            ty_val    => 16#03C0
        ),
        -- Hexagram 27: Corners of the Mouth
        26 => make_hexagram(
            id_val    => 27,
            yao_val   => 33,
            up_tri    => 2,
            lo_tri    => 4,
            cat_val   => 2,
            act_val   => 1,
            agt_val   => 1,
            dom_val   => 1,
            elem_val  => 2,
            coder_val => 2,
            rs3_val   => 6,
            mot_val   => 0,
            voice_val => 2,
            intent_val=> 0,
            dens_val  => 1,
            vtx_val   => 16#002F,
            suc_val   => 16#0002,
            chaos_val => 16#1818,
            whims_val => 16#200E,
            dark_val  => 16#1004,
            coh_val   => 16#7019,
            vw_val    => 16#7626,
            intens_val=> 16#0A3D,
            tx_val    => 16#F4C0,
            ty_val    => 16#03C0
        ),
        -- Hexagram 28: Preponderance of the
        27 => make_hexagram(
            id_val    => 28,
            yao_val   => 30,
            up_tri    => 5,
            lo_tri    => 6,
            cat_val   => 1,
            act_val   => 2,
            agt_val   => 2,
            dom_val   => 2,
            elem_val  => 5,
            coder_val => 3,
            rs3_val   => 7,
            mot_val   => 0,
            voice_val => 2,
            intent_val=> 0,
            dens_val  => 1,
            vtx_val   => 16#003F,
            suc_val   => 16#0002,
            chaos_val => 16#148C,
            whims_val => 16#2801,
            dark_val  => 16#1C92,
            coh_val   => 16#7B0F,
            vw_val    => 16#855B,
            intens_val=> 16#0A3D,
            tx_val    => 16#FC40,
            ty_val    => 16#03C0
        ),
        -- Hexagram 29: The Abysmal
        28 => make_hexagram(
            id_val    => 29,
            yao_val   => 18,
            up_tri    => 3,
            lo_tri    => 3,
            cat_val   => 1,
            act_val   => 3,
            agt_val   => 2,
            dom_val   => 3,
            elem_val  => 3,
            coder_val => 4,
            rs3_val   => 8,
            mot_val   => 0,
            voice_val => 7,
            intent_val=> 0,
            dens_val  => 1,
            vtx_val   => 16#004E,
            suc_val   => 16#0002,
            chaos_val => 16#251B,
            whims_val => 16#1A24,
            dark_val  => 16#2844,
            coh_val   => 16#5D4A,
            vw_val    => 16#6D47,
            intens_val=> 16#0A3D,
            tx_val    => 16#03C0,
            ty_val    => 16#03C0
        ),
        -- Hexagram 30: The Clinging
        29 => make_hexagram(
            id_val    => 30,
            yao_val   => 45,
            up_tri    => 7,
            lo_tri    => 7,
            cat_val   => 3,
            act_val   => 2,
            agt_val   => 3,
            dom_val   => 2,
            elem_val  => 7,
            coder_val => 5,
            rs3_val   => 9,
            mot_val   => 0,
            voice_val => 2,
            intent_val=> 0,
            dens_val  => 1,
            vtx_val   => 16#005E,
            suc_val   => 16#0001,
            chaos_val => 16#135D,
            whims_val => 16#19CF,
            dark_val  => 16#1DC0,
            coh_val   => 16#7FCA,
            vw_val    => 16#8A53,
            intens_val=> 16#0A3D,
            tx_val    => 16#0B40,
            ty_val    => 16#03C0
        ),
        -- Hexagram 31: Influence
        30 => make_hexagram(
            id_val    => 31,
            yao_val   => 14,
            up_tri    => 4,
            lo_tri    => 6,
            cat_val   => 2,
            act_val   => 1,
            agt_val   => 1,
            dom_val   => 1,
            elem_val  => 4,
            coder_val => 6,
            rs3_val   => 0,
            mot_val   => 0,
            voice_val => 2,
            intent_val=> 0,
            dens_val  => 1,
            vtx_val   => 16#006E,
            suc_val   => 16#0001,
            chaos_val => 16#10FF,
            whims_val => 16#1E69,
            dark_val  => 16#1811,
            coh_val   => 16#7ECB,
            vw_val    => 16#7EA4,
            intens_val=> 16#0A3D,
            tx_val    => 16#12C0,
            ty_val    => 16#03C0
        ),
        -- Hexagram 32: Duration
        31 => make_hexagram(
            id_val    => 32,
            yao_val   => 28,
            up_tri    => 5,
            lo_tri    => 2,
            cat_val   => 3,
            act_val   => 3,
            agt_val   => 3,
            dom_val   => 3,
            elem_val  => 5,
            coder_val => 7,
            rs3_val   => 1,
            mot_val   => 0,
            voice_val => 2,
            intent_val=> 0,
            dens_val  => 1,
            vtx_val   => 16#0000,
            suc_val   => 16#0002,
            chaos_val => 16#1818,
            whims_val => 16#26B1,
            dark_val  => 16#15B3,
            coh_val   => 16#7793,
            vw_val    => 16#7CDE,
            intens_val=> 16#0A3D,
            tx_val    => 16#1A40,
            ty_val    => 16#03C0
        ),
        -- Hexagram 33: Retreat
        32 => make_hexagram(
            id_val    => 33,
            yao_val   => 15,
            up_tri    => 4,
            lo_tri    => 0,
            cat_val   => 3,
            act_val   => 1,
            agt_val   => 3,
            dom_val   => 1,
            elem_val  => 4,
            coder_val => 8,
            rs3_val   => 2,
            mot_val   => 0,
            voice_val => 2,
            intent_val=> 0,
            dens_val  => 0,
            vtx_val   => 16#0015,
            suc_val   => 16#0000,
            chaos_val => 16#0D73,
            whims_val => 16#1059,
            dark_val  => 16#201E,
            coh_val   => 16#8375,
            vw_val    => 16#8AEB,
            intens_val=> 16#0A3D,
            tx_val    => 16#E5C0,
            ty_val    => 16#FC40
        ),
        -- Hexagram 34: Power of the Great
        33 => make_hexagram(
            id_val    => 34,
            yao_val   => 60,
            up_tri    => 0,
            lo_tri    => 2,
            cat_val   => 0,
            act_val   => 0,
            agt_val   => 0,
            dom_val   => 0,
            elem_val  => 0,
            coder_val => 9,
            rs3_val   => 3,
            mot_val   => 0,
            voice_val => 2,
            intent_val=> 0,
            dens_val  => 1,
            vtx_val   => 16#002A,
            suc_val   => 16#0001,
            chaos_val => 16#148C,
            whims_val => 16#1772,
            dark_val  => 16#1BFA,
            coh_val   => 16#7F33,
            vw_val    => 16#8C1A,
            intens_val=> 16#0A3D,
            tx_val    => 16#ED40,
            ty_val    => 16#FC40
        ),
        -- Hexagram 35: Progress
        34 => make_hexagram(
            id_val    => 35,
            yao_val   => 5,
            up_tri    => 1,
            lo_tri    => 7,
            cat_val   => 2,
            act_val   => 2,
            agt_val   => 1,
            dom_val   => 2,
            elem_val  => 1,
            coder_val => 10,
            rs3_val   => 4,
            mot_val   => 0,
            voice_val => 2,
            intent_val=> 0,
            dens_val  => 2,
            vtx_val   => 16#003F,
            suc_val   => 16#0001,
            chaos_val => 16#0E0A,
            whims_val => 16#1BEA,
            dark_val  => 16#0BE0,
            coh_val   => 16#758A,
            vw_val    => 16#76DC,
            intens_val=> 16#0A3D,
            tx_val    => 16#F4C0,
            ty_val    => 16#FC40
        ),
        -- Hexagram 36: Darkening of the Lig
        35 => make_hexagram(
            id_val    => 36,
            yao_val   => 40,
            up_tri    => 7,
            lo_tri    => 1,
            cat_val   => 1,
            act_val   => 3,
            agt_val   => 2,
            dom_val   => 3,
            elem_val  => 7,
            coder_val => 11,
            rs3_val   => 5,
            mot_val   => 0,
            voice_val => 2,
            intent_val=> 0,
            dens_val  => 1,
            vtx_val   => 16#0054,
            suc_val   => 16#0001,
            chaos_val => 16#0FD0,
            whims_val => 16#1E47,
            dark_val  => 16#0C78,
            coh_val   => 16#745B,
            vw_val    => 16#7737,
            intens_val=> 16#0A3D,
            tx_val    => 16#FC40,
            ty_val    => 16#FC40
        ),
        -- Hexagram 37: The Family
        36 => make_hexagram(
            id_val    => 37,
            yao_val   => 43,
            up_tri    => 7,
            lo_tri    => 5,
            cat_val   => 2,
            act_val   => 1,
            agt_val   => 1,
            dom_val   => 1,
            elem_val  => 7,
            coder_val => 0,
            rs3_val   => 6,
            mot_val   => 0,
            voice_val => 2,
            intent_val=> 0,
            dens_val  => 0,
            vtx_val   => 16#0068,
            suc_val   => 16#0001,
            chaos_val => 16#135D,
            whims_val => 16#1E8B,
            dark_val  => 16#1DC0,
            coh_val   => 16#7D6D,
            vw_val    => 16#87F6,
            intens_val=> 16#0A3D,
            tx_val    => 16#03C0,
            ty_val    => 16#FC40
        ),
        -- Hexagram 38: Opposition
        37 => make_hexagram(
            id_val    => 38,
            yao_val   => 53,
            up_tri    => 6,
            lo_tri    => 7,
            cat_val   => 1,
            act_val   => 2,
            agt_val   => 2,
            dom_val   => 2,
            elem_val  => 6,
            coder_val => 1,
            rs3_val   => 7,
            mot_val   => 0,
            voice_val => 2,
            intent_val=> 0,
            dens_val  => 1,
            vtx_val   => 16#007D,
            suc_val   => 16#0002,
            chaos_val => 16#1523,
            whims_val => 16#2475,
            dark_val  => 16#1BFA,
            coh_val   => 16#7E04,
            vw_val    => 16#8832,
            intens_val=> 16#0A3D,
            tx_val    => 16#0B40,
            ty_val    => 16#FC40
        ),
        -- Hexagram 39: Obstruction
        38 => make_hexagram(
            id_val    => 39,
            yao_val   => 20,
            up_tri    => 4,
            lo_tri    => 3,
            cat_val   => 1,
            act_val   => 3,
            agt_val   => 2,
            dom_val   => 3,
            elem_val  => 4,
            coder_val => 2,
            rs3_val   => 8,
            mot_val   => 0,
            voice_val => 2,
            intent_val=> 0,
            dens_val  => 2,
            vtx_val   => 16#0092,
            suc_val   => 16#0001,
            chaos_val => 16#16E9,
            whims_val => 16#185D,
            dark_val  => 16#1BD9,
            coh_val   => 16#6C31,
            vw_val    => 16#729A,
            intens_val=> 16#0A3D,
            tx_val    => 16#12C0,
            ty_val    => 16#FC40
        ),
        -- Hexagram 40: Deliverance
        39 => make_hexagram(
            id_val    => 40,
            yao_val   => 10,
            up_tri    => 3,
            lo_tri    => 2,
            cat_val   => 2,
            act_val   => 2,
            agt_val   => 1,
            dom_val   => 2,
            elem_val  => 3,
            coder_val => 3,
            rs3_val   => 9,
            mot_val   => 0,
            voice_val => 2,
            intent_val=> 0,
            dens_val  => 1,
            vtx_val   => 16#0000,
            suc_val   => 16#0003,
            chaos_val => 16#22BE,
            whims_val => 16#1EDF,
            dark_val  => 16#1D9F,
            coh_val   => 16#6334,
            vw_val    => 16#70D4,
            intens_val=> 16#0A3D,
            tx_val    => 16#1A40,
            ty_val    => 16#FC40
        ),
        -- Hexagram 41: Decrease
        40 => make_hexagram(
            id_val    => 41,
            yao_val   => 35,
            up_tri    => 6,
            lo_tri    => 4,
            cat_val   => 2,
            act_val   => 1,
            agt_val   => 1,
            dom_val   => 1,
            elem_val  => 6,
            coder_val => 4,
            rs3_val   => 0,
            mot_val   => 0,
            voice_val => 2,
            intent_val=> 0,
            dens_val  => 1,
            vtx_val   => 16#001A,
            suc_val   => 16#0001,
            chaos_val => 16#12C5,
            whims_val => 16#2453,
            dark_val  => 16#164B,
            coh_val   => 16#7D5F,
            vw_val    => 16#7E49,
            intens_val=> 16#0A3D,
            tx_val    => 16#E5C0,
            ty_val    => 16#F4C0
        ),
        -- Hexagram 42: Increase
        41 => make_hexagram(
            id_val    => 42,
            yao_val   => 49,
            up_tri    => 2,
            lo_tri    => 5,
            cat_val   => 2,
            act_val   => 0,
            agt_val   => 1,
            dom_val   => 0,
            elem_val  => 2,
            coder_val => 5,
            rs3_val   => 1,
            mot_val   => 0,
            voice_val => 2,
            intent_val=> 0,
            dens_val  => 1,
            vtx_val   => 16#0034,
            suc_val   => 16#0002,
            chaos_val => 16#1A76,
            whims_val => 16#24EB,
            dark_val  => 16#15B3,
            coh_val   => 16#7793,
            vw_val    => 16#7DB2,
            intens_val=> 16#0A3D,
            tx_val    => 16#ED40,
            ty_val    => 16#F4C0
        ),
        -- Hexagram 43: Breakthrough
        42 => make_hexagram(
            id_val    => 43,
            yao_val   => 62,
            up_tri    => 0,
            lo_tri    => 6,
            cat_val   => 0,
            act_val   => 0,
            agt_val   => 0,
            dom_val   => 0,
            elem_val  => 0,
            coder_val => 6,
            rs3_val   => 2,
            mot_val   => 0,
            voice_val => 2,
            intent_val=> 0,
            dens_val  => 1,
            vtx_val   => 16#004E,
            suc_val   => 16#0001,
            chaos_val => 16#1C7F,
            whims_val => 16#1B0F,
            dark_val  => 16#22D8,
            coh_val   => 16#82AF,
            vw_val    => 16#9497,
            intens_val=> 16#0A3D,
            tx_val    => 16#F4C0,
            ty_val    => 16#F4C0
        ),
        -- Hexagram 44: Coming to Meet
        43 => make_hexagram(
            id_val    => 44,
            yao_val   => 31,
            up_tri    => 5,
            lo_tri    => 0,
            cat_val   => 3,
            act_val   => 3,
            agt_val   => 3,
            dom_val   => 3,
            elem_val  => 5,
            coder_val => 7,
            rs3_val   => 3,
            mot_val   => 0,
            voice_val => 2,
            intent_val=> 0,
            dens_val  => 1,
            vtx_val   => 16#0068,
            suc_val   => 16#0002,
            chaos_val => 16#1C7F,
            whims_val => 16#1C3E,
            dark_val  => 16#249F,
            coh_val   => 16#7FB9,
            vw_val    => 16#91A2,
            intens_val=> 16#0A3D,
            tx_val    => 16#FC40,
            ty_val    => 16#F4C0
        ),
        -- Hexagram 45: Gathering Together
        44 => make_hexagram(
            id_val    => 45,
            yao_val   => 6,
            up_tri    => 1,
            lo_tri    => 6,
            cat_val   => 2,
            act_val   => 1,
            agt_val   => 1,
            dom_val   => 1,
            elem_val  => 1,
            coder_val => 8,
            rs3_val   => 4,
            mot_val   => 0,
            voice_val => 2,
            intent_val=> 0,
            dens_val  => 1,
            vtx_val   => 16#0083,
            suc_val   => 16#0001,
            chaos_val => 16#0F39,
            whims_val => 16#2303,
            dark_val  => 16#0AB1,
            coh_val   => 16#745B,
            vw_val    => 16#7571,
            intens_val=> 16#0A3D,
            tx_val    => 16#03C0,
            ty_val    => 16#F4C0
        ),
        -- Hexagram 46: Pushing Upward
        45 => make_hexagram(
            id_val    => 46,
            yao_val   => 24,
            up_tri    => 5,
            lo_tri    => 1,
            cat_val   => 2,
            act_val   => 2,
            agt_val   => 1,
            dom_val   => 2,
            elem_val  => 5,
            coder_val => 9,
            rs3_val   => 5,
            mot_val   => 0,
            voice_val => 2,
            intent_val=> 0,
            dens_val  => 1,
            vtx_val   => 16#009D,
            suc_val   => 16#0001,
            chaos_val => 16#0FD0,
            whims_val => 16#2560,
            dark_val  => 16#0C78,
            coh_val   => 16#70CE,
            vw_val    => 16#73AA,
            intens_val=> 16#0A3D,
            tx_val    => 16#0B40,
            ty_val    => 16#F4C0
        ),
        -- Hexagram 47: Oppression
        46 => make_hexagram(
            id_val    => 47,
            yao_val   => 22,
            up_tri    => 3,
            lo_tri    => 6,
            cat_val   => 1,
            act_val   => 3,
            agt_val   => 2,
            dom_val   => 3,
            elem_val  => 3,
            coder_val => 10,
            rs3_val   => 6,
            mot_val   => 0,
            voice_val => 2,
            intent_val=> 0,
            dens_val  => 1,
            vtx_val   => 16#00B7,
            suc_val   => 16#0002,
            chaos_val => 16#1F31,
            whims_val => 16#202F,
            dark_val  => 16#247D,
            coh_val   => 16#6FE3,
            vw_val    => 16#7951,
            intens_val=> 16#0A3D,
            tx_val    => 16#12C0,
            ty_val    => 16#F4C0
        ),
        -- Hexagram 48: The Well
        47 => make_hexagram(
            id_val    => 48,
            yao_val   => 26,
            up_tri    => 5,
            lo_tri    => 3,
            cat_val   => 3,
            act_val   => 1,
            agt_val   => 3,
            dom_val   => 1,
            elem_val  => 5,
            coder_val => 11,
            rs3_val   => 7,
            mot_val   => 0,
            voice_val => 2,
            intent_val=> 0,
            dens_val  => 1,
            vtx_val   => 16#0000,
            suc_val   => 16#0002,
            chaos_val => 16#1A76,
            whims_val => 16#21F6,
            dark_val  => 16#2059,
            coh_val   => 16#71A9,
            vw_val    => 16#7951,
            intens_val=> 16#0A3D,
            tx_val    => 16#1A40,
            ty_val    => 16#F4C0
        ),
        -- Hexagram 49: Revolution
        48 => make_hexagram(
            id_val    => 49,
            yao_val   => 46,
            up_tri    => 7,
            lo_tri    => 6,
            cat_val   => 2,
            act_val   => 0,
            agt_val   => 1,
            dom_val   => 0,
            elem_val  => 7,
            coder_val => 0,
            rs3_val   => 8,
            mot_val   => 0,
            voice_val => 2,
            intent_val=> 0,
            dens_val  => 2,
            vtx_val   => 16#001F,
            suc_val   => 16#0001,
            chaos_val => 16#148C,
            whims_val => 16#20E8,
            dark_val  => 16#1C92,
            coh_val   => 16#7E9B,
            vw_val    => 16#88E8,
            intens_val=> 16#0A3D,
            tx_val    => 16#E5C0,
            ty_val    => 16#ED40
        ),
        -- Hexagram 50: The Cauldron
        49 => make_hexagram(
            id_val    => 50,
            yao_val   => 29,
            up_tri    => 5,
            lo_tri    => 7,
            cat_val   => 0,
            act_val   => 0,
            agt_val   => 0,
            dom_val   => 0,
            elem_val  => 5,
            coder_val => 1,
            rs3_val   => 9,
            mot_val   => 0,
            voice_val => 2,
            intent_val=> 0,
            dens_val  => 1,
            vtx_val   => 16#003F,
            suc_val   => 16#0001,
            chaos_val => 16#135D,
            whims_val => 16#20E8,
            dark_val  => 16#1DC0,
            coh_val   => 16#7C3E,
            vw_val    => 16#86C7,
            intens_val=> 16#0A3D,
            tx_val    => 16#ED40,
            ty_val    => 16#ED40
        ),
        -- Hexagram 51: The Arousing
        50 => make_hexagram(
            id_val    => 51,
            yao_val   => 36,
            up_tri    => 2,
            lo_tri    => 2,
            cat_val   => 0,
            act_val   => 0,
            agt_val   => 0,
            dom_val   => 0,
            elem_val  => 2,
            coder_val => 2,
            rs3_val   => 0,
            mot_val   => 0,
            voice_val => 2,
            intent_val=> 0,
            dens_val  => 0,
            vtx_val   => 16#005E,
            suc_val   => 16#0003,
            chaos_val => 16#1F31,
            whims_val => 16#25F8,
            dark_val  => 16#0DA7,
            coh_val   => 16#6C13,
            vw_val    => 16#7626,
            intens_val=> 16#0A3D,
            tx_val    => 16#F4C0,
            ty_val    => 16#ED40
        ),
        -- Hexagram 52: Keeping Still
        51 => make_hexagram(
            id_val    => 52,
            yao_val   => 9,
            up_tri    => 4,
            lo_tri    => 4,
            cat_val   => 3,
            act_val   => 3,
            agt_val   => 3,
            dom_val   => 3,
            elem_val  => 4,
            coder_val => 3,
            rs3_val   => 1,
            mot_val   => 0,
            voice_val => 6,
            intent_val=> 0,
            dens_val  => 1,
            vtx_val   => 16#007D,
            suc_val   => 16#0001,
            chaos_val => 16#0D73,
            whims_val => 16#172F,
            dark_val  => 16#1391,
            coh_val   => 16#7621,
            vw_val    => 16#7626,
            intens_val=> 16#0A3D,
            tx_val    => 16#FC40,
            ty_val    => 16#ED40
        ),
        -- Hexagram 53: Development
        52 => make_hexagram(
            id_val    => 53,
            yao_val   => 11,
            up_tri    => 4,
            lo_tri    => 5,
            cat_val   => 2,
            act_val   => 2,
            agt_val   => 1,
            dom_val   => 2,
            elem_val  => 4,
            coder_val => 4,
            rs3_val   => 2,
            mot_val   => 0,
            voice_val => 2,
            intent_val=> 0,
            dens_val  => 2,
            vtx_val   => 16#009D,
            suc_val   => 16#0001,
            chaos_val => 16#0FD0,
            whims_val => 16#1C0B,
            dark_val  => 16#1940,
            coh_val   => 16#7D9C,
            vw_val    => 16#7DB2,
            intens_val=> 16#0A3D,
            tx_val    => 16#03C0,
            ty_val    => 16#ED40
        ),
        -- Hexagram 54: The Marrying Maiden
        53 => make_hexagram(
            id_val    => 54,
            yao_val   => 52,
            up_tri    => 6,
            lo_tri    => 2,
            cat_val   => 1,
            act_val   => 1,
            agt_val   => 2,
            dom_val   => 1,
            elem_val  => 6,
            coder_val => 5,
            rs3_val   => 3,
            mot_val   => 0,
            voice_val => 2,
            intent_val=> 0,
            dens_val  => 1,
            vtx_val   => 16#00BC,
            suc_val   => 16#0002,
            chaos_val => 16#19DE,
            whims_val => 16#2A3D,
            dark_val  => 16#13ED,
            coh_val   => 16#795A,
            vw_val    => 16#7E49,
            intens_val=> 16#0A3D,
            tx_val    => 16#0B40,
            ty_val    => 16#ED40
        ),
        -- Hexagram 55: Abundance
        54 => make_hexagram(
            id_val    => 55,
            yao_val   => 13,
            up_tri    => 7,
            lo_tri    => 2,
            cat_val   => 0,
            act_val   => 0,
            agt_val   => 0,
            dom_val   => 0,
            elem_val  => 7,
            coder_val => 6,
            rs3_val   => 4,
            mot_val   => 0,
            voice_val => 2,
            intent_val=> 0,
            dens_val  => 0,
            vtx_val   => 16#00DB,
            suc_val   => 16#0002,
            chaos_val => 16#1818,
            whims_val => 16#1F98,
            dark_val  => 16#15B3,
            coh_val   => 16#7B20,
            vw_val    => 16#806A,
            intens_val=> 16#0A3D,
            tx_val    => 16#12C0,
            ty_val    => 16#ED40
        ),
        -- Hexagram 56: The Wanderer
        55 => make_hexagram(
            id_val    => 56,
            yao_val   => 44,
            up_tri    => 4,
            lo_tri    => 7,
            cat_val   => 1,
            act_val   => 2,
            agt_val   => 2,
            dom_val   => 2,
            elem_val  => 4,
            coder_val => 7,
            rs3_val   => 5,
            mot_val   => 0,
            voice_val => 2,
            intent_val=> 0,
            dens_val  => 1,
            vtx_val   => 16#0000,
            suc_val   => 16#0001,
            chaos_val => 16#0FD0,
            whims_val => 16#1750,
            dark_val  => 16#1940,
            coh_val   => 16#7FF9,
            vw_val    => 16#800F,
            intens_val=> 16#0A3D,
            tx_val    => 16#1A40,
            ty_val    => 16#ED40
        ),
        -- Hexagram 57: The Gentle
        56 => make_hexagram(
            id_val    => 57,
            yao_val   => 27,
            up_tri    => 5,
            lo_tri    => 5,
            cat_val   => 3,
            act_val   => 1,
            agt_val   => 3,
            dom_val   => 1,
            elem_val  => 5,
            coder_val => 8,
            rs3_val   => 6,
            mot_val   => 0,
            voice_val => 2,
            intent_val=> 0,
            dens_val  => 1,
            vtx_val   => 16#0025,
            suc_val   => 16#0001,
            chaos_val => 16#135D,
            whims_val => 16#25A4,
            dark_val  => 16#1DC0,
            coh_val   => 16#79E0,
            vw_val    => 16#8469,
            intens_val=> 16#0A3D,
            tx_val    => 16#E5C0,
            ty_val    => 16#E5C0
        ),
        -- Hexagram 58: The Joyous
        57 => make_hexagram(
            id_val    => 58,
            yao_val   => 54,
            up_tri    => 6,
            lo_tri    => 6,
            cat_val   => 2,
            act_val   => 1,
            agt_val   => 1,
            dom_val   => 1,
            elem_val  => 6,
            coder_val => 9,
            rs3_val   => 7,
            mot_val   => 0,
            voice_val => 8,
            intent_val=> 0,
            dens_val  => 1,
            vtx_val   => 16#0049,
            suc_val   => 16#0002,
            chaos_val => 16#1652,
            whims_val => 16#2B8E,
            dark_val  => 16#1ACB,
            coh_val   => 16#7CD5,
            vw_val    => 16#86C7,
            intens_val=> 16#0A3D,
            tx_val    => 16#ED40,
            ty_val    => 16#E5C0
        ),
        -- Hexagram 59: Dispersion
        58 => make_hexagram(
            id_val    => 59,
            yao_val   => 19,
            up_tri    => 3,
            lo_tri    => 5,
            cat_val   => 1,
            act_val   => 2,
            agt_val   => 2,
            dom_val   => 2,
            elem_val  => 3,
            coder_val => 10,
            rs3_val   => 8,
            mot_val   => 0,
            voice_val => 2,
            intent_val=> 0,
            dens_val  => 1,
            vtx_val   => 16#006E,
            suc_val   => 16#0002,
            chaos_val => 16#1E02,
            whims_val => 16#1DD2,
            dark_val  => 16#25AC,
            coh_val   => 16#6EB4,
            vw_val    => 16#785F,
            intens_val=> 16#0A3D,
            tx_val    => 16#F4C0,
            ty_val    => 16#E5C0
        ),
        -- Hexagram 60: Limitation
        59 => make_hexagram(
            id_val    => 60,
            yao_val   => 50,
            up_tri    => 6,
            lo_tri    => 3,
            cat_val   => 3,
            act_val   => 3,
            agt_val   => 3,
            dom_val   => 3,
            elem_val  => 6,
            coder_val => 11,
            rs3_val   => 9,
            mot_val   => 0,
            voice_val => 2,
            intent_val=> 0,
            dens_val  => 1,
            vtx_val   => 16#0092,
            suc_val   => 16#0002,
            chaos_val => 16#1C3C,
            whims_val => 16#2582,
            dark_val  => 16#1E93,
            coh_val   => 16#736F,
            vw_val    => 16#7ABD,
            intens_val=> 16#0A3D,
            tx_val    => 16#FC40,
            ty_val    => 16#E5C0
        ),
        -- Hexagram 61: Inner Truth
        60 => make_hexagram(
            id_val    => 61,
            yao_val   => 51,
            up_tri    => 6,
            lo_tri    => 5,
            cat_val   => 2,
            act_val   => 1,
            agt_val   => 1,
            dom_val   => 1,
            elem_val  => 6,
            coder_val => 0,
            rs3_val   => 0,
            mot_val   => 0,
            voice_val => 2,
            intent_val=> 0,
            dens_val  => 1,
            vtx_val   => 16#00B7,
            suc_val   => 16#0002,
            chaos_val => 16#1523,
            whims_val => 16#2930,
            dark_val  => 16#1BFA,
            coh_val   => 16#7BA6,
            vw_val    => 16#85D5,
            intens_val=> 16#0A3D,
            tx_val    => 16#03C0,
            ty_val    => 16#E5C0
        ),
        -- Hexagram 62: Preponderance of the
        61 => make_hexagram(
            id_val    => 62,
            yao_val   => 12,
            up_tri    => 2,
            lo_tri    => 4,
            cat_val   => 1,
            act_val   => 3,
            agt_val   => 2,
            dom_val   => 3,
            elem_val  => 2,
            coder_val => 1,
            rs3_val   => 1,
            mot_val   => 0,
            voice_val => 2,
            intent_val=> 0,
            dens_val  => 1,
            vtx_val   => 16#00DB,
            suc_val   => 16#0002,
            chaos_val => 16#1818,
            whims_val => 16#200E,
            dark_val  => 16#1004,
            coh_val   => 16#7019,
            vw_val    => 16#7626,
            intens_val=> 16#0A3D,
            tx_val    => 16#0B40,
            ty_val    => 16#E5C0
        ),
        -- Hexagram 63: After Completion
        62 => make_hexagram(
            id_val    => 63,
            yao_val   => 42,
            up_tri    => 7,
            lo_tri    => 3,
            cat_val   => 3,
            act_val   => 3,
            agt_val   => 3,
            dom_val   => 3,
            elem_val  => 7,
            coder_val => 2,
            rs3_val   => 2,
            mot_val   => 0,
            voice_val => 2,
            intent_val=> 0,
            dens_val  => 1,
            vtx_val   => 16#0100,
            suc_val   => 16#0002,
            chaos_val => 16#1A76,
            whims_val => 16#1ADD,
            dark_val  => 16#2059,
            coh_val   => 16#7536,
            vw_val    => 16#7CDE,
            intens_val=> 16#0A3D,
            tx_val    => 16#12C0,
            ty_val    => 16#E5C0
        ),
        -- Hexagram 64: Before Completion
        63 => make_hexagram(
            id_val    => 64,
            yao_val   => 21,
            up_tri    => 3,
            lo_tri    => 7,
            cat_val   => 2,
            act_val   => 2,
            agt_val   => 1,
            dom_val   => 2,
            elem_val  => 3,
            coder_val => 3,
            rs3_val   => 3,
            mot_val   => 0,
            voice_val => 2,
            intent_val=> 0,
            dens_val  => 1,
            vtx_val   => 16#0000,
            suc_val   => 16#0002,
            chaos_val => 16#1E02,
            whims_val => 16#1916,
            dark_val  => 16#25AC,
            coh_val   => 16#7112,
            vw_val    => 16#7ABD,
            intens_val=> 16#0A3D,
            tx_val    => 16#1A40,
            ty_val    => 16#E5C0
        )
    );

    ---------------------------------------------------------------------------
    -- OEIS A000000 density map (64 terms, period 32)
    ---------------------------------------------------------------------------
    constant C_DENSITY_MAP : t_density_array := (
        "00", "01", "10", "01", "00", "01", "10", "01",
        "01", "01", "01", "01", "01", "01", "01", "01",
        "10", "01", "00", "01", "10", "01", "00", "01",
        "01", "01", "01", "01", "01", "01", "01", "01",
        "00", "01", "10", "01", "00", "01", "10", "01",
        "01", "01", "01", "01", "01", "01", "01", "01",
        "10", "01", "00", "01", "10", "01", "00", "01",
        "01", "01", "01", "01", "01", "01", "01", "01"
    );

    ---------------------------------------------------------------------------
    -- Function body
    ---------------------------------------------------------------------------
    function make_hexagram(
        id_val   : integer;
        yao_val  : integer;
        up_tri   : integer;
        lo_tri   : integer;
        cat_val  : integer;
        act_val  : integer;
        agt_val  : integer;
        dom_val  : integer;
        elem_val : integer;
        coder_val: integer;
        rs3_val  : integer;
        mot_val  : integer;
        voice_val: integer;
        intent_val: integer;
        dens_val : integer;
        vtx_val  : integer;
        suc_val  : integer;
        chaos_val: integer;
        whims_val: integer;
        dark_val : integer;
        coh_val  : integer;
        vw_val   : integer;
        intens_val: integer;
        tx_val   : integer;
        ty_val   : integer
    ) return t_hexagram is
        variable h : t_hexagram;
    begin
        h.id             := to_unsigned(id_val, 7);
        h.yao            := to_unsigned(yao_val, 6);
        h.upper_trigram  := to_unsigned(up_tri, 3);
        h.lower_trigram  := to_unsigned(lo_tri, 3);
        h.category       := to_unsigned(cat_val, 2);
        h.action         := to_unsigned(act_val, 2);
        h.agent          := to_unsigned(agt_val, 2);
        h.domain         := to_unsigned(dom_val, 2);
        h.element        := to_unsigned(elem_val, 3);
        h.coder          := to_unsigned(coder_val, 4);
        h.rs3            := to_unsigned(rs3_val, 4);
        h.motion         := std_logic(to_unsigned(mot_val, 1)(0));
        h.voice          := to_unsigned(voice_val, 4);
        h.intent         := to_unsigned(intent_val, 4);
        h.density        := to_unsigned(dens_val, 2);
        h.vortex_tension := to_signed(vtx_val, 16);
        h.suction        := to_unsigned(suc_val, 16);
        h.chaos          := to_unsigned(chaos_val, 16);
        h.whimsy         := to_unsigned(whims_val, 16);
        h.dark           := to_unsigned(dark_val, 16);
        h.coherence      := to_unsigned(coh_val, 16);
        h.voice_weight   := to_unsigned(vw_val, 16);
        h.intensity      := to_unsigned(intens_val, 16);
        h.tx             := to_signed(tx_val, 16);
        h.ty             := to_signed(ty_val, 16);
        return h;
    end function;

end package king_wen_shotgun_pkg;
