/**
 * CollisionVisLoader — Parses BVH JSONs into Three.js collision geometry.
 * Loads from DATASETS/collisionvis_physics/ generated by Shap-E pipeline.
 */
import * as THREE from 'three';

export interface BVHNode {
  min: [number, number, number];
  max: [number, number, number];
  children?: BVHNode[];
  isLeaf: boolean;
}

export interface CollisionVisData {
  kitId: number;
  aabb: { min: [number, number, number]; max: [number, number, number] };
  boundingSphere: { center: [number, number, number]; radius: number };
  bvh?: BVHNode;
  vertexCount: number;
  faceCount: number;
}

export class CollisionVisLoader {
  private cache = new Map<number, CollisionVisData>();
  private baseUrl: string;

  constructor(baseUrl: string) {
    this.baseUrl = baseUrl;
  }

  async loadBVH(kitId: number): Promise<CollisionVisData | null> {
    if (this.cache.has(kitId)) return this.cache.get(kitId)!;

    try {
      const res = await fetch(`${this.baseUrl}/collision/${kitId}`);
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      const data: CollisionVisData = await res.json();
      this.cache.set(kitId, data);
      return data;
    } catch (err) {
      console.warn(`[COLLISION] Failed to load BVH for kit ${kitId}:`, err);
      return null;
    }
  }

  /** Convert BVH to Three.js Box3 for raycast acceleration */
  toBox3(data: CollisionVisData): THREE.Box3 {
    return new THREE.Box3(
      new THREE.Vector3(...data.aabb.min),
      new THREE.Vector3(...data.aabb.max)
    );
  }

  /** Convert BVH to Three.js Sphere for broad-phase culling */
  toSphere(data: CollisionVisData): THREE.Sphere {
    return new THREE.Sphere(
      new THREE.Vector3(...data.boundingSphere.center),
      data.boundingSphere.radius
    );
  }

  /** Recursively visualize BVH tree as wireframe boxes */
  visualizeBVH(data: CollisionVisData, scene: THREE.Scene, depth: number = 0): void {
    const color = this.depthColor(depth);
    if (data.bvh) {
      this.visualizeNode(data.bvh, scene, color, depth);
    } else if (data.aabb) {
      this.visualizeNode({ min: data.aabb.min, max: data.aabb.max, isLeaf: true }, scene, color, depth);
    }
  }

  private visualizeNode(node: BVHNode, scene: THREE.Scene, color: number, depth: number): void {
    const size: [number, number, number] = [
      node.max[0] - node.min[0],
      node.max[1] - node.min[1],
      node.max[2] - node.min[2],
    ];
    const center: [number, number, number] = [
      (node.min[0] + node.max[0]) / 2,
      (node.min[1] + node.max[1]) / 2,
      (node.min[2] + node.max[2]) / 2,
    ];

    const geo = new THREE.BoxGeometry(size[0], size[1], size[2]);
    const mat = new THREE.MeshBasicMaterial({
      color,
      wireframe: true,
      transparent: true,
      opacity: Math.max(0.1, 0.5 - depth * 0.05),
    });
    const mesh = new THREE.Mesh(geo, mat);
    mesh.position.set(center[0], center[1], center[2]);
    scene.add(mesh);

    if (node.children) {
      for (const child of node.children) {
        this.visualizeNode(child, scene, this.depthColor(depth + 1), depth + 1);
      }
    }
  }

  private depthColor(depth: number): number {
    const colors = [0x00ff00, 0xffff00, 0xff8800, 0xff0000, 0xff00ff, 0x00ffff];
    return colors[depth % colors.length];
  }
}
